rules:
  - id: hardcoded-api-key
    pattern-either:
      - pattern: |
          $API_KEY = "..."
      - pattern: |
          const $API_KEY = "..."
      - pattern: |
          let $API_KEY = "..."
      - pattern: |
          var $API_KEY = "..."
    message: |
      Hardcoded API key detected. This is a security risk as it exposes sensitive credentials in your source code.
    languages: [javascript, typescript]
    severity: ERROR
    metadata:
      category: security
      technology: [javascript, typescript]
      confidence: HIGH

  - id: hardcoded-password
    pattern-either:
      - pattern: |
          $PASSWORD = "..."
      - pattern: |
          const $PASSWORD = "..."
      - pattern: |
          let $PASSWORD = "..."
      - pattern: |
          var $PASSWORD = "..."
    message: |
      Hardcoded password detected. Passwords should be stored securely and not in source code.
    languages: [javascript, typescript]
    severity: ERROR
    metadata:
      category: security
      technology: [javascript, typescript]
      confidence: HIGH

  - id: sql-injection-risk
    pattern-either:
      - pattern: |
          $QUERY = "SELECT * FROM users WHERE id = " + $INPUT
      - pattern: |
          $QUERY = `SELECT * FROM users WHERE id = ${$INPUT}`
    message: |
      Potential SQL injection vulnerability. Use parameterized queries instead.
    languages: [javascript, typescript]
    severity: WARNING
    metadata:
      category: security
      technology: [javascript, typescript]
      confidence: MEDIUM

  - id: console-log-in-production
    pattern: console.log(...)
    message: |
      Console.log statements should be removed before production deployment.
    languages: [javascript, typescript]
    severity: INFO
    metadata:
      category: security
      technology: [javascript, typescript]
      confidence: LOW
