rules:
  - id: xss-vulnerability
    pattern: |
      $ELEMENT.innerHTML = $USER_INPUT
    message: "Potential XSS vulnerability. Sanitize user input or use textContent instead."
    languages:
      - javascript
      - typescript
    severity: WARNING
    metadata:
      category: security
      subcategory: xss

  - id: eval-usage
    pattern: |
      eval($INPUT)
    message: "Use of eval() is dangerous and can lead to code injection attacks."
    languages:
      - javascript
      - typescript
    severity: ERROR
    metadata:
      category: security
      subcategory: injection

  - id: insecure-random
    pattern-either:
      - pattern: |
          Math.random()
      - pattern: |
          new Date().getTime()
    message: "Insecure random number generation. Use crypto.randomBytes() for security-sensitive operations."
    languages:
      - javascript
      - typescript
    severity: INFO
    metadata:
      category: security
      subcategory: crypto
